<?php
$username = "";
$password = "";
$profile = "";
$userid = "";
if(isset($_SESSION['user']))
{
    $username = $_SESSION['user'];
}
if(isset($_SESSION['password']))
{
    $password = $_SESSION['password'];
}
if(isset($_SESSION['profile']))
{
    $profile = $_SESSION['profile'];
}
if(isset($_SESSION['iduser']))
{
    $userid = $_SESSION['iduser'];
}
?>
<!DOCTYPE html>
<html>
<head lang="en">
    <link rel="stylesheet" href="sources/css/main.css?<?php echo time(); ?>" />
    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <!--This is the CDN to connect with BootstrapCDN CSS-->
    <!-- JS AND JQUERY -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>    <meta charset="UTF-8">
    <!-- CDN FOR ICONS CART -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- CDN JS FUNCTIONS -->
    <script src="sources/js/functions.js?<?php echo time(); ?>"></script>
    <title>DealershipLuis</title>
</head>
<body class="margin">
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="left">
        <a class="navbar-brand" href="#">DEALERSHIP </a>|

        <?php
        if(isset($username))
        {
            if($username != "" and ($profile == 1 or $profile == 2))
            {
                echo '<a class="navbar-brand" href="#">&nbsp;CARS </a>|';
            }

            if($username != "" and $profile == 1)
            {
                ?>
                <a class="navbar-brand" href="#">&nbsp;USERS </a>|
                <?php
            }
        }
        ?>
    </div>
    <div class="right">
        <?php
        if(isset($username))
        {
            if($username != "")
            {
                echo '<a class="navbar-brand text-white">Welcome '.$username."</a>";
                echo '<a href="index.php?operation=logout" class="navbar-brand text-white cursor">LOGOUT</a>';
            }
            else
            {
                ?>
                <a class="navbar-brand text-white cursor" data-toggle="modal" data-target="#modallogin">LOGIN</a>|
                <a class="navbar-brand text-white cursor" data-toggle="modal" data-target="#modalsignup">&nbsp;SIGN UP </a>
                <?php
            }
        }
        ?>
    </div>
</nav>
<!-- Modal to new car -->
<div class="modal fade" id="modalnewcar" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">NEW CAR</h4>
                <button type="button" class="close" data-dismiss="modal">Go to Dealership</button>
            </div>
            <div class="modal-body">
                <form method="post" action="<?php echo htmlspecialchars("index.php?operation=newcar&userid=".$userid); ?>">
                    <div id="Brand">
                        *Brand:<br>
                        <input name="brand" type="text" class="form-control" placeholder="Brand">
                    </div>
                    <div id="Model">
                        *Model:<br>
                        <input name="model" type="text" class="form-control" placeholder="Model">
                    </div>
                    <div id="Year">
                        *Year:<br>
                        <input name="year" type="number" class="form-control" placeholder="Year">
                    </div>
                    <div id="Warranty">
                        *Warranty:<br>
                        <select name="warranty" class="form-control">
                            <option value=''>-Select one-</option>
                            <?php
                            $war = $carmodel->showwarraty();
                            foreach($war as $w)
                            {
                                echo "<option value='".$w['war_key_inside']."'>".$w['war_months']." Months</option>";
                            }
                            ?>
                        </select>
                    </div>
                    <div id="Price">
                        *Price:<br>
                        <input name="price" type="number" class="form-control" placeholder="Price">
                    </div>
                    <div id="Image">
                        *Image:<br>
                        <input name="image" type="file" class="form-control cursor">
                    </div>
                    <button type="submit" class="btn btn-info form-control">NEW CAR</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<!-- Modal to edit -->
<div class="modal fade" id="modaledit" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">BUY CAR</h4>
                <button type="button" class="close" data-dismiss="modal">Go to Dealership</button>
            </div>
            <div class="modal-body">
                <?php
                $idcar = $_GET['car_id'];
                $result = $carmodel->pricecar($idcar);
                ?>
                <form method="post" action="<?php echo htmlspecialchars("index.php?operation=confirmbuy&car_id=".$idcar."&userid=".$userid); ?>">
                    <div class="col-md-12">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" data-src="sources/images/<?php echo $result[0]['car_img']; ?>" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="sources/images/<?php echo $result[0]['car_img']; ?>" data-holder-rendered="true">
                            <div class="card-body">
                                <p class="card-text descriptionCar"><?php echo "$".number_format($result[0]['car_price'],2); ?></p>
                                <div class="d-flex justify-content-between align-items-center">
                                </div>
                            </div>
                        </div>
                    </div>
                    *Payment method:<br>
                    <select name="method" class="form-control" onchange="showmethod(this.value)">
                        <option value="">-Select method-</option>
                        <option value="cash">Cash</option>
                        <option value="loan">Loan</option>
                        <option value="both">Both</option>
                    </select>
                    <div id="cash">
                        *Cash:<br>
                        <input name="cash" type="number" class="form-control" placeholder="Cash">
                    </div>
                    <div id="loan">
                        *Loan:<br>
                        <input name="loan" type="text" class="form-control" placeholder="Loan">
                    </div>
                    <div id="time">
                        *Time loan:<br>
                        <select name="time" class="form-control">
                            <?php
                            $loans = $carmodel->showloans();
                            foreach($loans as $loa)
                            {
                                echo '<option value="'.$loa['lon_key_inside'].'">'.$loa['lon_months'].'</option>';
                            }
                            ?>
                        </select><br>
                    </div>
                    <button type="submit" class="btn btn-info form-control">BUY CAR</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Brand</th>
        <th scope="col">Model</th>
        <th scope="col">Year</th>
        <th scope="col">Warranty</th>
        <th scope="col">Price</th>
        <th scope="col">Image</th>
        <th scope="col">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalnewcar">
                New Car
            </button>
        </th>
    </tr>
    </thead>
    <tbody>
    <?php
    $data=$carmodel->showcars($userid);
    foreach($data as $dat)
    {
        ?>
        <tr>
            <td><?php echo $dat["car_brand"]; ?></td>
            <td><?php echo $dat["car_model"]; ?></td>
            <td><?php echo $dat["car_year"]; ?></td>
            <td><?php echo $dat["war_months"]; ?></td>
            <td><?php echo $dat["car_price"]; ?></td>
            <td><?php echo '<img src="sources/images/audi.jpg" class="imagecar">'; ?></td>
            <td><a class="fa fa-edit cursor" title="Edit" data-toggle="modal" data-target="#modaledit"><a></td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>

</body>
</html>