<?php
$username = "";
$password = "";
$profile = "";
$userid = "";
if(isset($_SESSION['user']))
{
    $username = $_SESSION['user'];
}
if(isset($_SESSION['password']))
{
    $password = $_SESSION['password'];
}
if(isset($_SESSION['profile']))
{
    $profile = $_SESSION['profile'];
}
if(isset($_SESSION['iduser']))
{
    $userid = $_SESSION['iduser'];
}
?>
<!DOCTYPE html>
<html>
<head lang="en">
    <link rel="stylesheet" href="sources/css/main.css?<?php echo time(); ?>" />
    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <!--This is the CDN to connect with BootstrapCDN CSS-->
    <!-- JS AND JQUERY -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>    <meta charset="UTF-8">
    <!-- CDN FOR ICONS CART -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- CDN JS FUNCTIONS -->
    <script src="sources/js/functions.js?<?php echo time(); ?>"></script>
    <!-- CDN by libraries for pictures -->
    <link rel="stylesheet" href="sources/lib/dropify-master/dist/css/dropify.css?<?php echo time(); ?>"/>
    <script src="sources/lib/dropify-master/dist/js/dropify.js"></script>
    <script src="upload.js"></script>
    <title>DealershipLuis</title>
</head>
<body class="margin">
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="left">
        <a class="navbar-brand" href="index.php?operation=gotodealership">DEALERSHIP </a>|

        <?php
        if(isset($username))
        {
            if($username != "" and ($profile == 1 or $profile == 2))
            {
                echo '<a class="navbar-brand" href="#">&nbsp;CARS </a>|';
            }

            if($username != "" and $profile == 1)
            {
                ?>
                <a class="navbar-brand" href="index.php?operation=gotousers">&nbsp;USERS </a>|
                <?php
            }
        }
        ?>
    </div>
    <div class="right">
        <?php
        if(isset($username))
        {
            if($username != "")
            {
                echo '<a class="navbar-brand text-white">Welcome '.$username."</a>";
                echo '<a href="index.php?operation=logout" class="navbar-brand text-white cursor">LOGOUT</a>';
            }
            else
            {
                ?>
                <a class="navbar-brand text-white cursor" data-toggle="modal" data-target="#modallogin">LOGIN</a>|
                <a class="navbar-brand text-white cursor" data-toggle="modal" data-target="#modalsignup">&nbsp;SIGN UP </a>
                <?php
            }
        }
        ?>
    </div>
</nav>
<!-- Modal to new car -->
<div class="modal fade" id="modalnewcar" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">NEW CAR TO SELL</h4>
                <button type="button" class="close" data-dismiss="modal">Go to Sell Cars</button>
            </div>
            <div class="modal-body">
                <form method="post" name="formcars" id="formcars" enctype="multipart/form-data" action="<?php echo htmlspecialchars("index.php?operation=newcar&userid=".$userid); ?>">
                    <div id="Brand">
                        *Brand:<br>
                        <input name="brand" type="text" class="form-control" placeholder="Brand">
                    </div>
                    <div id="Model">
                        *Model:<br>
                        <input name="model" type="text" class="form-control" placeholder="Model">
                    </div>
                    <div id="Year">
                        *Year:<br>
                        <input name="year" type="number" class="form-control" placeholder="Year">
                    </div>
                    <div id="Warranty">
                        *Warranty:<br>
                        <select name="warranty" class="form-control">
                            <option value=''>-Select one-</option>
                            <?php
                            $war = $carmodel->showwarraty();
                            foreach($war as $w)
                            {
                                echo "<option value='".$w['war_key_inside']."'>".$w['war_months']." Months</option>";
                            }
                            ?>
                        </select>
                    </div>
                    <div id="Price">
                        *Price:<br>
                        <input name="price" type="number" class="form-control" placeholder="Price">
                    </div>
                    <div id="Image">
                        *Image:<br>
                        <input type="file" id="imgcar" name="imgcar" data-allowed-file-extensions="png jpg gif jpge bmp" class="dropify profile-user-img img-responsive img-circle" data-default-file="" data-height="128"  data-min-width="128"  data-show-remove="false">
                    </div>
                    <button type="submit" class="btn btn-info form-control">NEW CAR TO SELL</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<!-- Modal to edit -->
<div class="modal fade" id="modaledit" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">EDIT CAR</h4>
                <button type="button" class="close" data-dismiss="modal">Go to Dealership</button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data" action="<?php echo htmlspecialchars("index.php?operation=editcar&userid=".$userid); ?>">
                    <div id="Brand">
                        *Brand:<br>
                        <input name="brand" id="brand" type="text" class="form-control" placeholder="Brand">
                    </div>
                    <div id="Model">
                        *Model:<br>
                        <input name="model" id="model" type="text" class="form-control" placeholder="Model">
                    </div>
                    <div id="Year">
                        *Year:<br>
                        <input name="year" id="year" type="number" class="form-control" placeholder="Year">
                    </div>
                    <div id="Warranty">
                        *Warranty:<br>
                        <select name="warranty" id="warranty" class="form-control">
                            <option value=''>-Select one-</option>
                            <?php
                            $war = $carmodel->showwarraty();
                            foreach($war as $w)
                            {
                                echo "<option value='".$w['war_key_inside']."'>".$w['war_months']." Months</option>";
                            }
                            ?>
                        </select>
                    </div>
                    <div id="Price">
                        *Price:<br>
                        <input name="price" id="price" type="number" class="form-control" placeholder="Price">
                    </div>
                    <img src="" id="neweditpicture" class="imagecar">
                    <div id="Image">
                        *Image:<br>
                        <input type="file" value="" id="imgcaredit" name="imgcaredit" data-allowed-file-extensions="png jpg gif jpge bmp" class="dropify profile-user-img img-responsive img-circle" data-default-file="" data-height="128"  data-min-width="128"  data-show-remove="false">
                    </div>
                    <input type="hidden" name="idcarhidden" id="idcarhidden" value="">
                    <button type="submit" class="btn btn-info form-control">EDIT CAR TO SELL</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<h2>Search by Brand or Model</h2>
<input type="text" name="search" class="form-control" placeholder="Search by Brand or Model" onkeyup="searchcar(this.value,<?php echo $userid; ?>)">
<table class="table">
    <thead>
    <tr>
        <th scope="col">Brand</th>
        <th scope="col">Model</th>
        <th scope="col">Year</th>
        <th scope="col">Warranty</th>
        <th scope="col">Price</th>
        <th scope="col">Image</th>
        <th scope="col"></th>
        <th scope="col">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalnewcar">
                New Car to sell
            </button>
        </th>
    </tr>
    </thead>
    <tbody id="rowscars">
    <?php
    $data=$carmodel->showcars($userid);
    foreach($data as $dat)
    {
        ?>
        <tr id="rowcar<?php echo $dat["car_key_inside"]; ?>">
            <td><?php echo $dat["car_brand"]; ?></td>
            <td><?php echo $dat["car_model"]; ?></td>
            <td><?php echo $dat["car_year"]; ?></td>
            <td><?php echo $dat["war_months"]; ?></td>
            <td><?php echo $dat["car_price"]; ?></td>
            <td><?php echo '<img src="sources/images/'.$dat["car_img"].'" class="imagecar">'; ?></td>
            <td><a class="fa fa-edit cursor" onclick="editsellcar('<?php echo $dat["car_key_inside"]; ?>')" title="Edit"><a></td>
            <td><a class="fa fa-trash cursor" onclick="deletecar('<?php echo $dat["car_key_inside"]; ?>')" title="Delete"><a></td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function(){
        // Basic
        $('.dropify').dropify();

        // Translated
        $('.dropify-fr').dropify({
            messages: {
                default: 'Glissez-déposez un fichier ici ou cliquez',
                replace: 'Glissez-déposez un fichier ou cliquez pour remplacer',
                remove:  'Supprimer',
                error:   'Désolé, le fichier trop volumineux'
            }
        });

        // Used events
        var drEvent = $('#input-file-events').dropify();

        drEvent.on('dropify.beforeClear', function(event, element){
            return confirm("Do you really want to delete \"" + element.file.name + "\" ?");
        });

        drEvent.on('dropify.afterClear', function(event, element){
            alert('File deleted');
        });

        drEvent.on('dropify.errors', function(event, element){
            console.log('Has Errors');
        });

        var drDestroy = $('#input-file-to-destroy').dropify();
        drDestroy = drDestroy.data('dropify')
        $('#toggleDropify').on('click', function(e){
            e.preventDefault();
            if (drDestroy.isDropified()) {
                drDestroy.destroy();
            } else {
                drDestroy.init();
            }
        })
    });
</script>
</body>
</html>