<?php
$username = "";
$password = "";
$profile = "";
if(isset($_SESSION['user']))
{
    $username = $_SESSION['user'];
}
if(isset($_SESSION['password']))
{
    $password = $_SESSION['password'];
}
if(isset($_SESSION['profile']))
{
    $profile = $_SESSION['profile'];
}
?>
<!DOCTYPE html>
<html>
<head lang="en">
    <link rel="stylesheet" href="sources/css/main.css?<?php echo time(); ?>" />
    <!-- CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <!--This is the CDN to connect with BootstrapCDN CSS-->
    <!-- JS AND JQUERY -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>    <meta charset="UTF-8">
    <!-- CDN FOR ICONS CART -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- CDN JS FUNCTIONS -->
    <script src="sources/js/functions.js?<?php echo time(); ?>"></script>
    <title>DealershipLuis</title>
</head>
<body class="margin">
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="left">
        <a class="navbar-brand" href="#">DEALERSHIP </a>|
        <?php
        if(isset($username))
        {
            if($username != "" and $profile == 1)
            {
                ?>
                <a class="navbar-brand" href="#">&nbsp;CARS </a>|
                <a class="navbar-brand" href="#">&nbsp;USERS </a>|
                <?php
            }
        }
        ?>
    </div>
    <div class="right">
        <?php
        if(isset($username))
        {
            if($username != "")
            {
                echo '<a class="navbar-brand text-white">Welcome '.$username."</a>";
                echo '<a href="index.php?operation=logout" class="navbar-brand text-white cursor">LOGOUT</a>';
            }
            else
            {
                ?>
                <a class="navbar-brand text-white cursor" data-toggle="modal" data-target="#modallogin">LOGIN</a>|
                <a class="navbar-brand text-white cursor" data-toggle="modal" data-target="#modalsignup">&nbsp;SIGN UP </a>
                <?php
            }
        }
        ?>
    </div>
</nav>
<!-- Modal -->
<div class="modal fade" id="modallogin" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">LOGIN</h4>
                <button type="button" class="close" data-dismiss="modal">Go to Dealership</button>
            </div>
            <div class="modal-body">
                <form method="post" action="<?php echo htmlspecialchars("index.php?operation=login"); ?>">
                    User:<br>
                    <input name="user" type="text" class="form-control" placeholder="User"><br>
                    Password:<br>
                    <input name="password" type="password" class="form-control" placeholder="Password"><br>
                    <button type="submit" class="btn btn-info form-control">LOGIN</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="modalsignup" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">SIGN UP</h4>
                <button type="button" class="close" data-dismiss="modal">Go to Dealership</button>
            </div>
            <div class="modal-body">
                <form method="post" action="<?php echo htmlspecialchars("index.php?operation=signup"); ?>">
                    *Username:<br>
                    <input name="user" type="text" class="form-control" placeholder="User">
                    *Password:<br>
                    <input name="password" type="password" class="form-control" placeholder="Password">
                    *Name:<br>
                    <input name="name" type="text" class="form-control" placeholder="Name">
                    LastName:<br>
                    <input name="lastname" type="text" class="form-control" placeholder="LastName">
                    *Email:<br>
                    <input name="email" type="text" class="form-control" placeholder="Email">
                    Phone:<br>
                    <input name="phone" type="text" class="form-control" placeholder="Phone">
                    Address:<br>
                    <input name="address" type="text" class="form-control" placeholder="Address"><br>
                    <button type="submit" class="btn btn-info form-control">SIGNUP</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
<div class="row">
    <?php
    $cars = $carmodel->showcars();
    foreach($cars as $key)
    {
        ?>
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="sources/images/<?php echo $key['car_img']; ?>" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="sources/images/<?php echo $key['car_img']; ?>" data-holder-rendered="true">
                <div class="card-body">
                    <p class="card-text descriptionCar"><?php echo $key['car_brand']; ?></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <small class="text-muted">
                            <a href="index.php?operation=buy&car_id=<?php echo $key['car_key_inside']; ?>" class="btn btn-success text-white cursor form-control">
                                BUY
                            </a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    <?php
    }
    ?>
</div>
</body>
</html>